import { Resend } from 'resend'

export default async function sendNewsLetter(subject: string, content: string, key: string) {
  // eslint-disable-next-line node/prefer-global/process
  const resend = new Resend(key)
  const { data, error } = await resend.emails.send({
    from: 'ShimaRin <shima.notify@nickchen.top>',
    to: ['i@nickchen.top'],
    subject,
    html: `${content}\n\nGenerated by <a href="https://github.com/nick-cjyx9/ShimaRSS">Shima RSS</a>`,
  })
  if (error)
    throw error
  return data?.id
}
